### ISSUE TITLE
No converter found for return value of type

### ISSUE THREAD

**Issue by smallAttr** [rkonovalov/jfilter#1]
Hello author:
    Today. I am curious to build a demo. I found a meanning thing that If I didn't indicate the produces {produces = {MediaType.APPLICATION_JSON_VALUE}} in RequestMapping . throws org.springframework.http.converter.HttpMessageNotWritableException: No converter found for return value of type: class com.github.smallAttr.domain.User]. debugged for a long time.  discover getProducibleMediaTypes() in AbstractMessageConverterMethodProcessor.java return null. 
The problem appears on this code：

     else if (converter.canWrite(valueClass, null)) {
	  result.addAll(converter.getSupportedMediaTypes());
     }

and your implementation class {FilterConverter} evaluates this expression {converter.canWrite(valueClass, null)} return false. I found the comment of the method {boolean canWrite(Class<?> clazz, @Nullable MediaType mediaType)} allow media type can be null. If not specified. typically the value of an accept header.
     finally. simply solution is that: 

      @Override
    public boolean canWrite(Class<?> aClass, MediaType mediaType) {
        return supportedMedia.indexOf(mediaType) >= 0 || Objects.isNull(mediaType);
    }

Best practice:
I think you would like to inherit AbstractHttpMessageConverter rather than implement HttpMessageConverter.

**Comment by rkonovalov** [comment]
Hello, smallAttr.

After some tests I had same issue. You are right, media type could be null.
I have added your fix in repository.

Thank you for helping and interesting! :)
