### ISSUE TITLE
How to Pass fields to be filtered as arraylist from controller ? For Dynamic Filtering Case

### ISSUE THREAD

**Issue by ZaheerUdDeen** [rkonovalov/jfilter#10]
@DynamicFilterComponent
    public class DemoIdFilter implements DynamicFilterEvent {
        @Override
        public FilterFields onGetFilterFields(MethodParameter methodParameter, RequestSession request) {
    
            //If request has SOME_KEY in request params then try to filter object
            if(request.getRequest().getParameterMap().containsKey("SOME_KEY")) {
                return new FilterFields(User.class, `Arrays.asList("id", "password", "email")`);
            } else
                return new FilterFields();
        }
    }

**Arrays.asList("id", "password", "email")**
    Can I pass this arraylist from controller?

**Comment by rkonovalov** [comment]
Hello @ZaheerUdDeen,

You can pass configured FilterFields by using session attribute and DynamicSessionFilter will proccess it.

In your controller you can add next request(as example):
`
    @DynamicFilter(DynamicSessionFilter.class)
    @RequestMapping(value = "/dynamicRequest",
            params = {"email", "password"}, 
			method = RequestMethod.POST,
            consumes = {MediaType.APPLICATION_FORM_URLENCODED_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE})
    public User signInUser(HttpSession session,  @RequestParam("email") String email, @RequestParam("password") String password) {
        
		//Set configured FilterFields into session's ATTRIBUTE_FILTER_FIELDS attribute		
		session.setAttribute(DynamicSessionFilter.ATTRIBUTE_FILTER_FIELDS, FilterFields.getFieldsBy(Arrays.asList("id", "password", "email")));
		
		//DynamicSessionFilter will check ATTRIBUTE_FILTER_FIELDS in session attributes and if ATTRIBUTE_FILTER_FIELDS has FilterFields
		//it will filter current response 
        return databaseService.getUser(email, password);
    }
`

**Comment by rkonovalov** [comment]
I added example in manual
[Passing filter fields through controller](https://rkonovalov.github.io/projects/jfilter/1.0.14/examples/filter-dynamic/)

**Comment by ZaheerUdDeen** [comment]
Thanks a lot, you can close it!
