### ISSUE TITLE
how can i use my own MappingJackson2HttpMessageConverter

### ISSUE THREAD

**Issue by fraillove** [rkonovalov/jfilter#11]
there is a setting `filterConfiguration.setUseDefaultConverters(true);`

but the default converter is not suit for my requirement, i want to use my own MappingJackson2HttpMessageConverter how can i configure it.
&
how can i change some behaveior of ObjectMapper such as  configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
but still use the library's objectmapper

thanks in advance!

**Comment by fraillove** [comment]
and my custom RestControllerAdvice i wanna wrap my api result don't work either, the library is so intrusive.

**Comment by rkonovalov** [comment]
Hello @fraillove,

1) In current version there is no possibility to use your own MappingJackson2HttpMessageConverter,
but I can add it in next release.
2) In current release you can build your own pre-configured ObjectMapper and set it in configuration
`
filterConfiguration.setMapper(APPLICATION_JSON, newObjectMapper);    
`
But certainly I can add more useful method for configure exist ObjectMappers

3) About your last question I need more details. Maybe you can show some of code example with your issue.

**Comment by rkonovalov** [comment]
Hello, @fraillove 
You can find more about configuring exist ObjectMappers and using custom MessageConverter by using link below: [JFilter Configuration](https://rkonovalov.github.io/projects/jfilter/1.0.17/configuration/)
