### ISSUE TITLE
Example for java.util.Optional

### ISSUE THREAD

**Issue by cachenbach** [rkonovalov/jfilter#12]
Hello @rkonovalov 

can you please give an example how I can filter Optionals?
Like this:

`public Optional<User> signIn(...){...}`

My naive approach return this response, although the object exists:

`{
    "empty": false,
    "present": true
}`

Thanks!
 Christian

**Comment by rkonovalov** [comment]
Hello, @cachenbach 

For current time JFilter doesn't support Optional type.
Issue binded with weird interaction of **Jdk8Module** and **SerializerFactory**
I need time to solve this issue. And I plan to release fix  in the next version.
Thank you for patience.

With regards,
Ruslan.

**Comment by rkonovalov** [comment]
Hello, @cachenbach 

Could you please check 1.0.17 version.

**Comment by rkonovalov** [comment]
Hello, @cachenbach 
In 1.0.17 has been fixed issue with Optional type.
More information about configuring filtration you can find by following link:
[Simple field filter](https://rkonovalov.github.io/projects/jfilter/1.0.17/examples/filter-field/)
