### ISSUE TITLE
Any method to set a global / default produces?

### ISSUE THREAD

**Issue by ShineYang** [rkonovalov/jfilter#13]
If I use @FieldFilterSetting annotation on the Controller method, the default Content-type will be changed to application/xml, is there a way to set a global produces when I use jfilter?  because I just want to exclude some fields of object.
Thanks!

**Comment by rkonovalov** [comment]
Hello, @ShineYang 
Current version doesn't supports setting default produce MediaType. I can add it in next version.
Also you can try to use **"Default Spring message converters"** by changing configuration settings:
`filterConfiguration.setUseDefaultConverters(true);`

For more details please follow link: https://rkonovalov.github.io/projects/jfilter/1.0.16/configuration/
Chapter: **Using default Spring message converters**

**Comment by rkonovalov** [comment]
Also, did you specified "produces" in **RequestMapping** annotation?
There is examples of annotation: https://rkonovalov.github.io/projects/jfilter/1.0.16/examples/filter-field/

**Comment by ShineYang** [comment]
> Also, did you specified "produces" in **RequestMapping** annotation?
> There is examples of annotation: https://rkonovalov.github.io/projects/jfilter/1.0.16/examples/filter-field/
 Thank you sincerely!
