### ISSUE TITLE
Add support for different authentication types

### ISSUE THREAD

**Issue by ThE-MaRaC** [rkonovalov/jfilter#14]
**Is your feature request related to a problem? Please describe.**
We would like to use jfilter with OAuth and filter response depending on the user role(s).

**Describe the solution you'd like**
Get identity of the principal being authenticated, extract authorities granted to the user and compare them with the authorities that are provided via annotation.
For example:
```
private boolean hideField(List<String> roles) {
  Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
  if (principal != null && principal instanceof User) {
    User user = (User) principal;
    Collection<? extends GrantedAuthority> authorities = user.getAuthorities();
    for (GrantedAuthority auth : authorities) {
      if (roles.contains(auth.getAuthority())) {
        return true;
      }
    }
    return false;
  }
  return false;
}
```

**Describe alternatives you've considered**
Enable session management and copy roles into the session and then use SessionStrategy filter.

**Additional context**
NO

**Comment by rkonovalov** [comment]
Hi @ThE-MaRaC ,

You can use DynamicFilter feature
Example [Spring Security filter example](https://rkonovalov.github.io/projects/jfilter/1.0.17/examples/filter-dynamic/#spring-security-filter-example)

You just need to create new DynamicSecurityFilter class and use it by adding annotation in controller class
` @DynamicFilter(DynamicSessionFilter.class)
    @RequestMapping(value = "/someRequest"
....
`

**Comment by ThE-MaRaC** [comment]
Thx for info.
