### ISSUE TITLE
Allow to combine filters

### ISSUE THREAD

**Issue by njuro** [rkonovalov/jfilter#16]
Hello, thanks for this nice project. Recently I ran into use case, which is not covered in the documentation. I want to annotate my endpoint with `@FieldFilterSettings`, i.e. to always exclude some fields, but I want to apply additional `@DynamicFilter` on the same endpoint, which can potentially exclude another field (based on user's permissions in this case). I found out that in `FilterAdvice` the dynamic filter is not even invoked, when basic filter is found. Would it be possible to modify this behaviour and merge the excluded fields from all filters applied to endpoint?

Thanks.

**Comment by rkonovalov** [comment]
Hi @njuro 

Thank you for interest.
I thought about this functionality earlier and I think it possible to add this feature.
But I have a question, why you don't want to use `@DynamicFilter` with multiple conditions?
Link to [Multiple conditions filter](https://rkonovalov.github.io/projects/jfilter/1.0.17/examples/filter-dynamic/#multiple-conditions-filter-example)

By using `@DynamicFilter` with multiple conditions you can keep all filtering logic in one class.
Therefore, if necessary, you can reuse it in another parts of controller just by adding only one annotation instead of several.

**Comment by njuro** [comment]
Thanks @rkonovalov for prompt response. I thought about your proposed workaround, but I think that wouldn't work good for me. For example, let's say I have two endpoints, both of them produce entity `E` as response. In both of them I want to remove attribute `A` (if the user has not right permissions, so I use `DynamicFilter` here), but only on one of them I want to remove attribute `B` which has nothing to do with authorities, or any other logic I could use in filter class itself to distinguish between those two (maybe just by checking the actual request URL, but that feels kind of hack-y). I think merging the results of all filters applied to endpoint would be more intuitive :)

**Comment by njuro** [comment]
Any plans for this, @rkonovalov ?

**Comment by rkonovalov** [comment]
Hi @njuro 

Excuse me for long response.
I am plan to add this feature in next version.

**Comment by njuro** [comment]
Hello @rkonovalov 

Since it has been time, I made the change and opened pull request (see #21). Could you take a look at it please and merge if it's okay? Thank you.

**Comment by anil-manjappa** [comment]
Hello @rkonovalov

Can you share an example in case filtering  fields with complex type in a model/class, I am having complex type Author in Book class, when try to filter only with author i am getting empty object, I set filter behaviour "FilterBehaviour.KEEP_FIELDS"

http://localhost:8080/api/books/book?selectAttributes=author

response: author	{}

**Comment by rkonovalov** [comment]
Hi @anil-manjappa 
Please use this manual https://rkonovalov.github.io/projects/jfilter/1.0.17/examples/filter-field/#multiple-field-filtration

**Comment by rkonovalov** [comment]
Hi @njuro 
Added changes, you can check it.

**Comment by njuro** [comment]
Hey @rkonovalov looks good to me :) Do you plan to release new version on Maven soon?

**Comment by rkonovalov** [comment]
Hi @njuro 
On beginning of the next week or earlier.
