### ISSUE TITLE
Allow @DynamicFilter on class level

### ISSUE THREAD

**Issue by noahzuch** [rkonovalov/jfilter#18]
**Problem**
The `@DynamicFilter` annotation currently only works on method level. It would be very helpful to be able to define this annotation on class level as well (The target scope already includes Type, but the annotation is ignored by jfilter).

**Solution**
Pickup `@DynamicFilter` annotation on class level.

**Comment by rkonovalov** [comment]
Hi @noahzuch 
Sorry for long response. 
This issue will be fixed in next release 1.0.18

**Comment by noahzuch** [comment]
Hi,
happy to here that.

BR Noah Zuch

rkonovalov <notifications@github.com> schrieb am Do., 16. Juli 2020, 07:00:
