### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot subclass final class com.jfilter.components.FileWatcher

### ISSUE THREAD

**Issue by B0BAI** [rkonovalov/jfilter#2]
Hi @rkonovalov,

I'm trying to set up jfilter in my project. I did follow the steps you provided with zero success.
Can you help in any way?

Thanks.

**Comment by rkonovalov** [comment]
Hello,

Have you read this article https://dzone.com/articles/spring-web-service-response-filtering
If so, could you please add full stack of error, version of Spring Framework which you used.

With regards,
Ruslan

**Comment by B0BAI** [comment]
Hey Ruslan, Thanks for your response, but I have decided to stick with `SimpleFilterProvider`.

**Comment by B0BAI** [comment]
Thanks for your reply but I will be using `SimpleFilterProvider`.
