### ISSUE TITLE
Feature request: Add the original request to the RequestSession

### ISSUE THREAD

**Issue by ZoidbergVA** [rkonovalov/jfilter#6]
Hello @rkonovalov . 
For my use of jfilter, i need to use a dynamic filter that only filters fields if there was a particular query param in the request. I imagine that this is a common use case. The query params can be obtained from ServerHttpRequest (getRequest()).getServletRequest().getParameterMap()). 
So i propose you add either the whole ServerHttpRequest or at least the parameterMap to the RequestSession. 
Thanks.

**Comment by rkonovalov** [comment]
Hello @ZoidbergVA 
I have added HttpServletRequest in RequestSession, so you will have full access to request values in 1.0.11 version
As example you could create next DynamicFilter:

@DynamicFilterComponent
public class DemoIdFilter implements DynamicFilterEvent {
    @Override
    public FilterFields onGetFilterFields(MethodParameter methodParameter, RequestSession request) {

        //If request has SOME_KEY in request params then try to filter object
        if(request.getRequest().getParameterMap().containsKey("SOME_KEY")) {
            return new FilterFields(User.class, Arrays.asList("id", "password", "email"));
        } else
            return new FilterFields();
    }
}

Details about DynamicFilter can be found in https://rkonovalov.github.io/projects/jfilter/1.0.9/examples/filter-dynamic/

**Comment by ZoidbergVA** [comment]
Hello @rkonovalov 
I have tested this feature but unfortunately i found a bug. I have updated my repo (https://github.com/ZoidbergVA/json-ignore-issues) to show this. 

How you can replicate the issue:
1) clean install my repo
2) start the app
3) open http://localhost:8080/api/users in browser and you will see that you have all the fields of the UserDTO
4) open http://localhost:8080/api/users?small and you will see that you still have all the fields
5) close the app
6) open http://localhost:8080/api/users?small and you will see that you have only some fields
7) open http://localhost:8080/api/users and you will see that you still have only some fields

I believe you are caching the filter, and so maybe you are caching the request as well? As always, if you have any questions, i'm here to help. Thanks.

**Comment by rkonovalov** [comment]
Thank you for details of your issue.
Issue was in reusing of already created ObjectMapper.

After some research I have decided to reformat code and logic of working with ObjectMapper.
Reusing of already created and configured ObjectMapper leads to weird work of module.
Also, creating and configuring new ObjectMapper on each HTTP Request is inefficiently.
Therefore I have created Cache of ObjectMapper, which contains ObjectMappers per each method in Spring controller. It must to improve stability and speed. Also, I have added ability of adding/configuring ObjectMappers per each MediaType(you can create your own ObjectMapper for specified MediaType). Also you can enable/disable JFilter programmatically when you need. More details I will write in manuals of 1.0.12 version.

**Comment by rkonovalov** [comment]
Hello @ZoidbergVA 
I have released 1.0.12 version, so you can test it
Also added short manual about additional configuration of module
https://rkonovalov.github.io/projects/jfilter/1.0.12/configuration/

**Comment by ZoidbergVA** [comment]
Hello @rkonovalov. I have tested version 1.0.12 and indeed the issue is now fixed and the feature also works. You can close this issue. Thanks.
