### ISSUE TITLE
Feature request: Allow to specify field to keep

### ISSUE THREAD

**Issue by ZoidbergVA** [rkonovalov/jfilter#7]
Hello @rkonovalov .
For my use of jfilter, i have a lot of DTO's that i use a dynamic filter to filter them. I have a few fields in these DTO's that i always want to appear in the response, and a lot of fields that i don't always want to appear. It is common to add a new field, but usually these new fields are fields that i don't want to always appear in the response. So now i have a very big list of fields that i want filtered out, and this list is common to get even bigger. It would be nice if you allowed to specify fields that you want to keep. This would allow me to specify the small list of fields that i want to keep, and it would be less common that this list would change. 
Let me know if you need more details. 
Thanks.

**Comment by rkonovalov** [comment]
Hello @ZoidbergVA 
I have added FilterBehaviour parameter in JFilter annotations.
How to use it:
``java
@FieldFilterSetting(fields = {"id", "email"}, behaviour = FilterBehaviour.KEEP_FIELDS)
``
As result JFilter will hide all fields but not "id" and "email"

**Comment by ZoidbergVA** [comment]
Hello @rkonovalov 
I have tested this and it works perfectly, and it also works with DynamicFilters. 
I suggest maybe adding an example with DynamicFilter on the documentation as well, but it's no big deal. You can close the issue. 
Thanks.

**Comment by ZaheerUdDeen** [comment]
How to use it, dynamic filtering case ? kindly if you can provide an example big thanks.

**Comment by rkonovalov** [comment]
Hello, @ZaheerUdDeen 
All examples could be found in [Examples](https://rkonovalov.github.io/projects/jfilter/1.0.15/examples/)
If you have any questions, advice or issues please don't hesitate to ask.
