### ISSUE TITLE
can not filter field of Object in list

### ISSUE THREAD

**Issue by babay523** [rkonovalov/jfilter#8]
The return value is a List<User> of method in Controller, how can I config the filter column

**Comment by babay523** [comment]
In com.jfilter.components.FilterConverter line 61 
` //Serialize object with ObjectMapper
            objectMapper.writeValue(outputMessage.getBody(), wrapper.getObject());`
if I add 
`wrapper.getObject instance of List`
then  it can support List<Object> filter ?

**Comment by rkonovalov** [comment]
Hello @babay523 
To answer to your question I need example of your serialized object.
Filter hides fields in object only by field name, not by object type

**Comment by babay523** [comment]
for example:
`[
  {
    "id": 1,
    "customerNumber": "C1800540390",
    "balance": "23930.71",
    "currency": "CNY",
    "createDate": "2019-01-22 11:22:22"
  },
  {
    "id": 2,
    "customerNumber": "C1800540390",
    "balance": "23930.71",
    "currency": "CNY",
    "createDate": "2019-01-22 11:22:22"
  },
  {
    "id": 3,
    "customerNumber": "C1800540390",
    "balance": "23930.71",
    "currency": "CNY",
    "createDate": "2019-01-22 11:22:22"
  }
]`
can I filter column <balance>?

**Comment by rkonovalov** [comment]
Yes, you can add next annotation:
@FieldFilterSetting(fields = {"balance"})

For more details you can read Simple field filter manual:
https://rkonovalov.github.io/projects/jfilter/1.0.12/examples/filter-field/
